CREATE TABLE Product (
ProductID INT NOT NULL PRIMARY KEY,
Name VARCHAR(50) NOT NULL,
Description VARCHAR(1000) NOT NULL,
Price NUMBER NULL,
ImagePath VARCHAR(50) NULL,
OnCatalogPromotion NUMBER(1,0) NULL,
OnDepartmentPromotion NUMBER(1,0) NULL);

CREATE SEQUENCE ProductIDSeq;

CREATE OR REPLACE TRIGGER ProductAutonumberTrigger
BEFORE INSERT ON Product
FOR EACH ROW
BEGIN
   SELECT ProductIDSeq.NEXTVAL
   INTO :NEW.ProductID FROM DUAL;
END;
/
