CREATE TABLE Product (
ProductID INT GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
Name VARCHAR(50) NOT NULL,
Description VARCHAR(1000) NOT NULL,
Price DECIMAL(7,2),
ImagePath VARCHAR(50),
OnCatalogPromotion SMALLINT,
OnDepartmentPromotion SMALLINT);
