CREATE TABLE Category (
CategoryID INT GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
DepartmentID INT NOT NULL,
Name VARCHAR(50) NOT NULL,
Description VARCHAR (200),
FOREIGN KEY (DepartmentID) REFERENCES Department (DepartmentID));
