CREATE SCHEMA AUTHORIZATION System
GRANT SELECT ON FriendsNames TO Alice
CREATE VIEW FriendsNames AS SELECT Name FROM Friend
CREATE TABLE Friend (
   FriendID INT PRIMARY KEY NOT NULL, Name VARCHAR(50));
