CREATE TABLE Friend (Name VARCHAR(50) PRIMARY KEY NOT NULL, 
                     PhoneNo VARCHAR(15));

CREATE TABLE FriendAudit
(FriendAuditID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
 Operation VARCHAR(10),
 RecordedOn DATE DEFAULT CURRENT_DATE, 
 OldName VARCHAR(50),
 NewName VARCHAR(50),
 OldPhone VARCHAR(15),
 NewPhone VARCHAR(15));
